services:
  frontend:
    image: frontend
    container_name: studygroup_1_pet_clinic_frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8082:3000'
    networks:
     - pet_clinic_drama_network

networks:
 pet_clinic_drama_network:
   external: true